### ISSUE TITLE
Suggestion for where to contribute

### ISSUE THREAD

**Issue by xtuc** [welcome-to-open-source/ucla#14]
This event is a great idea, I know lots of people want to contribute but don't know where.

I recently launched a service which aggregate issues for beginners: https://contributor.ninja.

Discussion on Twitter: https://twitter.com/svensauleau/status/823189011044806658

I would be happy to make a PR if this is accepted.

Thanks,
Sven.

**Comment by gr2m** [comment]
@xtuc please do Sven, thanks for asking! I’ve seen contributor.ninja, I looked on GitHub if the source code is somewhere available to see how it works and then got distracted and than forgot about it :)

How do projects get at added to contributor.ninja? Say I’d like to add https://github.com/hoodiehq/camp, what’s the process?

**Comment by xtuc** [comment]
Great, thanks! I will make a PR for that.

Given that Contributor.ninja is still in development. It uses a static list of projects, I will add you manually.

I planning to open-source it in the future.

Edit: Where should I add a link to https://contributor.ninja?

**Comment by gr2m** [comment]
can you add a link below nteract in the READE? https://github.com/welcome-to-open-source/ucla#open-source-projects-and-issues-for-new-contributors?

**Comment by xtuc** [comment]
That's awesome, thanks :+1:
